stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test1test2/sample:v3
      pushRemote: true
      registry: index.docker.io
- name: 部署
  steps:
  - applyYamlConfig:
      path: ./tomcat7.yaml
timeout: 60
notification: {}
