stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/sample:v3
      pushRemote: true
      registry: 172.16.193.103
    env:
      PLUGIN_INSECURE: "true"  
- name: bushu
  steps:
  - applyYamlConfig:
      path: ./tomcat7.yaml
timeout: 60
notification: {}
